import { ExtractedField, PackageImage } from '../types';

export interface ExtractionResult {
  productName: string;
  brandName: string;
  category: string;
  extractedFields: ExtractedField[];
  rawDetectedText: string[];
}

export const extractionService = {
  /**
   * Simulates AI / OCR computer vision processing on package images.
   * Extracts structured legal declarations from principal display panel and statutory panels.
   */
  async extractDeclarationsFromImages(
    images: PackageImage[],
    presetHint?: string
  ): Promise<ExtractionResult> {
    // Simulate network and OCR processing time
    await new Promise((resolve) => setTimeout(resolve, 1400));

    // If preset hint matches, return pre-calibrated sample data
    if (presetHint === 'sample-noodles-01') {
      return {
        productName: 'Masala Magic Instant Noodles (70g)',
        brandName: 'Tasty Crunch Foods',
        category: 'Packaged Food & Cereals',
        rawDetectedText: [
          'TASTY CRUNCH FOODS',
          'MASALA MAGIC NOODLES',
          'Instant Wheat Noodles',
          'NET QUANTITY: 70 g',
          'MRP: ₹ 14.00 (Incl. of all taxes)',
          'USP: ₹ 0.20 / g',
          'Mfg Date: 12/08/2026',
          'Manufactured & Packed by: Tasty Crunch Foods India Pvt. Ltd.',
          'Plot No. 42-B, Industrial Area Phase II, Sonipat, Haryana - 131001',
          'FSSAI Lic. No. 10018021004523',
          'FOR CONSUMER COMPLAINTS / FEEDBACK: Write to Manager, Consumer Care at above manufacturer address',
          'Country of Origin: INDIA',
        ],
        extractedFields: [
          {
            id: `ef-${Date.now()}-1`,
            fieldKey: 'product_name',
            label: 'Product Name / Description',
            value: 'Masala Magic Noodles - Instant Wheat Noodles',
            confidence: 'HIGH',
            verificationState: 'DETECTED',
            sourceImageId: images[0]?.id || 'img-1',
            sourcePanel: 'Front Display Panel',
            bbox: { x: 10, y: 15, width: 80, height: 12 },
            legalReference: 'Rule 6(1)(a)',
          },
          {
            id: `ef-${Date.now()}-2`,
            fieldKey: 'manufacturer_name_address',
            label: 'Manufacturer & Packer Name & Address',
            value: 'Tasty Crunch Foods India Pvt. Ltd., Plot No. 42-B, Industrial Area Phase II, Sonipat, Haryana - 131001',
            confidence: 'HIGH',
            verificationState: 'DETECTED',
            sourceImageId: images[1]?.id || images[0]?.id || 'img-1',
            sourcePanel: 'Back Panel - Statutory Declarations',
            bbox: { x: 8, y: 13, width: 84, height: 14 },
            legalReference: 'Rule 6(1)(b)',
          },
          {
            id: `ef-${Date.now()}-3`,
            fieldKey: 'net_quantity',
            label: 'Net Quantity',
            value: '70 g',
            confidence: 'HIGH',
            verificationState: 'DETECTED',
            sourceImageId: images[0]?.id || 'img-1',
            sourcePanel: 'Front Display Panel',
            bbox: { x: 12, y: 68, width: 40, height: 6 },
            legalReference: 'Rule 6(1)(c)',
          },
          {
            id: `ef-${Date.now()}-4`,
            fieldKey: 'mrp',
            label: 'Retail Sale Price (MRP)',
            value: '₹ 14.00 (Incl. of all taxes)',
            confidence: 'HIGH',
            verificationState: 'DETECTED',
            sourceImageId: images[0]?.id || 'img-1',
            sourcePanel: 'Front Display Panel',
            bbox: { x: 12, y: 73, width: 50, height: 6 },
            legalReference: 'Rule 6(1)(e)',
          },
          {
            id: `ef-${Date.now()}-5`,
            fieldKey: 'unit_sale_price',
            label: 'Unit Sale Price (USP)',
            value: '₹ 0.20 / g',
            confidence: 'HIGH',
            verificationState: 'DETECTED',
            sourceImageId: images[0]?.id || 'img-1',
            sourcePanel: 'Front Display Panel',
            bbox: { x: 12, y: 77, width: 40, height: 5 },
            legalReference: 'Rule 6(11)',
          },
          {
            id: `ef-${Date.now()}-6`,
            fieldKey: 'date_of_manufacture',
            label: 'Date of Manufacture / Packaging',
            value: '12/08/2026',
            confidence: 'HIGH',
            verificationState: 'DETECTED',
            sourceImageId: images[1]?.id || images[0]?.id || 'img-1',
            sourcePanel: 'Back Panel',
            bbox: { x: 12, y: 56, width: 40, height: 5 },
            legalReference: 'Rule 6(1)(d)',
          },
          {
            id: `ef-${Date.now()}-7`,
            fieldKey: 'consumer_care',
            label: 'Consumer Care Contact Details',
            value: 'Write to Manager, Consumer Care at above manufacturer address [NO PHONE / EMAIL DETECTED]',
            confidence: 'MEDIUM',
            verificationState: 'UNCERTAIN',
            sourceImageId: images[1]?.id || images[0]?.id || 'img-1',
            sourcePanel: 'Back Panel - Statutory Declarations',
            bbox: { x: 8, y: 30, width: 84, height: 13 },
            legalReference: 'Rule 6(1)(f)',
          },
          {
            id: `ef-${Date.now()}-8`,
            fieldKey: 'country_of_origin',
            label: 'Country of Origin',
            value: 'INDIA',
            confidence: 'HIGH',
            verificationState: 'DETECTED',
            sourceImageId: images[1]?.id || images[0]?.id || 'img-1',
            sourcePanel: 'Back Panel',
            bbox: { x: 50, y: 64, width: 42, height: 8 },
            legalReference: 'Rule 6(1)(g)',
          },
        ],
      };
    }

    if (presetHint === 'sample-detergent-02') {
      return {
        productName: 'Sparkle Active Premium Detergent Powder',
        brandName: 'Sparkle Active',
        category: 'Household Care / Detergents',
        rawDetectedText: [
          'SPARKLE ACTIVE',
          'PREMIUM DETERGENT POWDER',
          'Net Qty: 450',
          'MRP: Rs. 65',
          'Sparkle Chemical Industries Ltd., Vapi, Gujarat - 396195',
          'Customer Care: 1800-456-1122',
        ],
        extractedFields: [
          {
            id: `ef-${Date.now()}-1`,
            fieldKey: 'product_name',
            label: 'Product Name',
            value: 'Sparkle Active Premium Detergent Powder',
            confidence: 'HIGH',
            verificationState: 'DETECTED',
            sourceImageId: images[0]?.id || 'img-1',
            sourcePanel: 'Front Panel',
            bbox: { x: 10, y: 8, width: 80, height: 10 },
            legalReference: 'Rule 6(1)(a)',
          },
          {
            id: `ef-${Date.now()}-2`,
            fieldKey: 'net_quantity',
            label: 'Net Quantity',
            value: '450 [Metric unit symbol missing]',
            confidence: 'HIGH',
            verificationState: 'DETECTED',
            sourceImageId: images[0]?.id || 'img-1',
            sourcePanel: 'Front Panel',
            bbox: { x: 8, y: 22, width: 84, height: 12 },
            legalReference: 'Rule 6(1)(c) & Rule 13',
          },
          {
            id: `ef-${Date.now()}-3`,
            fieldKey: 'mrp',
            label: 'Retail Sale Price (MRP)',
            value: 'Rs. 65 [Unit Sale Price Missing]',
            confidence: 'HIGH',
            verificationState: 'DETECTED',
            sourceImageId: images[0]?.id || 'img-1',
            sourcePanel: 'Front Panel',
            bbox: { x: 8, y: 32, width: 84, height: 8 },
            legalReference: 'Rule 6(1)(e)',
          },
          {
            id: `ef-${Date.now()}-4`,
            fieldKey: 'manufacturer_name_address',
            label: 'Manufacturer Details',
            value: 'Sparkle Chemical Industries Ltd., GIDC Phase IV, Vapi, Gujarat - 396195',
            confidence: 'HIGH',
            verificationState: 'DETECTED',
            sourceImageId: images[0]?.id || 'img-1',
            sourcePanel: 'Front Panel',
            bbox: { x: 8, y: 44, width: 84, height: 14 },
            legalReference: 'Rule 6(1)(b)',
          },
        ],
      };
    }

    if (presetHint === 'sample-oil-03') {
      return {
        productName: 'Golden Harvest Refined Sunflower Oil (1 Litre)',
        brandName: 'Golden Harvest Agro',
        category: 'Edible Oils & Fats',
        rawDetectedText: [
          'GOLDEN HARVEST AGRO',
          'REFINED SUNFLOWER OIL',
          'Net Volume: 1 L (1000 ml) / 910 g',
          'MRP: ₹ 165.00 (Incl. of all taxes)',
          'USP: ₹ 165.00 / L',
          'Date of Packaging: 15/09/2026',
          'Golden Harvest Agro Products Ltd., Pune, Maharashtra - 410501',
          'Toll-Free Helpline: 1800-222-7890',
        ],
        extractedFields: [
          {
            id: `ef-${Date.now()}-1`,
            fieldKey: 'product_name',
            label: 'Product Name',
            value: 'Refined Sunflower Oil',
            confidence: 'HIGH',
            verificationState: 'DETECTED',
            sourceImageId: images[0]?.id || 'img-1',
            sourcePanel: 'Front Panel',
            bbox: { x: 10, y: 12, width: 80, height: 8 },
            legalReference: 'Rule 6(1)(a)',
          },
          {
            id: `ef-${Date.now()}-2`,
            fieldKey: 'net_quantity',
            label: 'Net Quantity',
            value: '1 L (1000 ml) / 910 g',
            confidence: 'HIGH',
            verificationState: 'DETECTED',
            sourceImageId: images[0]?.id || 'img-1',
            sourcePanel: 'Front Panel',
            bbox: { x: 8, y: 24, width: 84, height: 16 },
            legalReference: 'Rule 6(1)(c)',
          },
          {
            id: `ef-${Date.now()}-3`,
            fieldKey: 'mrp',
            label: 'Maximum Retail Price (MRP)',
            value: '₹ 165.00 (Incl. of all taxes)',
            confidence: 'HIGH',
            verificationState: 'DETECTED',
            sourceImageId: images[0]?.id || 'img-1',
            sourcePanel: 'Front Panel',
            bbox: { x: 8, y: 28, width: 84, height: 10 },
            legalReference: 'Rule 6(1)(e)',
          },
          {
            id: `ef-${Date.now()}-4`,
            fieldKey: 'unit_sale_price',
            label: 'Unit Sale Price (USP)',
            value: '₹ 165.00 / L',
            confidence: 'HIGH',
            verificationState: 'DETECTED',
            sourceImageId: images[0]?.id || 'img-1',
            sourcePanel: 'Front Panel',
            bbox: { x: 8, y: 28, width: 84, height: 10 },
            legalReference: 'Rule 6(11)',
          },
          {
            id: `ef-${Date.now()}-5`,
            fieldKey: 'consumer_care',
            label: 'Consumer Care Cell',
            value: '1800-222-7890 | customercare@goldenharvestagro.com',
            confidence: 'HIGH',
            verificationState: 'DETECTED',
            sourceImageId: images[0]?.id || 'img-1',
            sourcePanel: 'Front Panel',
            bbox: { x: 8, y: 66, width: 84, height: 14 },
            legalReference: 'Rule 6(1)(f)',
          },
        ],
      };
    }

    // Default fallback extraction for user-uploaded custom images or photos
    return {
      productName: 'Scanned Packaged Commodity',
      brandName: 'Detected Commercial Brand',
      category: 'General Packaged Goods',
      rawDetectedText: [
        'PRE-PACKAGED COMMODITY LABEL',
        'BATCH NO: PR-2026-X',
        'NET WT: 250 g',
        'MRP: ₹ 95.00 (Incl. of all taxes)',
        'Mfd by: Enterprise Packagers Ltd.',
      ],
      extractedFields: [
        {
          id: `ef-${Date.now()}-1`,
          fieldKey: 'product_name',
          label: 'Product Name',
          value: 'Detected Packaged Commodity (Custom Upload)',
          confidence: 'MEDIUM',
          verificationState: 'DETECTED',
          sourceImageId: images[0]?.id || 'img-custom',
          sourcePanel: 'Primary Label',
          bbox: { x: 15, y: 15, width: 70, height: 15 },
          legalReference: 'Rule 6(1)(a)',
        },
        {
          id: `ef-${Date.now()}-2`,
          fieldKey: 'net_quantity',
          label: 'Net Quantity',
          value: '250 g',
          confidence: 'HIGH',
          verificationState: 'DETECTED',
          sourceImageId: images[0]?.id || 'img-custom',
          sourcePanel: 'Primary Label',
          bbox: { x: 15, y: 40, width: 35, height: 10 },
          legalReference: 'Rule 6(1)(c)',
        },
        {
          id: `ef-${Date.now()}-3`,
          fieldKey: 'mrp',
          label: 'Retail Sale Price (MRP)',
          value: '₹ 95.00 (Incl. of all taxes)',
          confidence: 'HIGH',
          verificationState: 'DETECTED',
          sourceImageId: images[0]?.id || 'img-custom',
          sourcePanel: 'Primary Label',
          bbox: { x: 15, y: 55, width: 45, height: 10 },
          legalReference: 'Rule 6(1)(e)',
        },
        {
          id: `ef-${Date.now()}-4`,
          fieldKey: 'manufacturer_name_address',
          label: 'Manufacturer / Packer Details',
          value: 'Enterprise Packagers Ltd., Sector 62, Noida, Uttar Pradesh - 201309',
          confidence: 'MEDIUM',
          verificationState: 'DETECTED',
          sourceImageId: images[0]?.id || 'img-custom',
          sourcePanel: 'Primary Label',
          bbox: { x: 15, y: 70, width: 70, height: 15 },
          legalReference: 'Rule 6(1)(b)',
        },
        {
          id: `ef-${Date.now()}-5`,
          fieldKey: 'consumer_care',
          label: 'Consumer Care Helpline',
          value: 'Contact Officer at factory address [Helpline unverified]',
          confidence: 'LOW',
          verificationState: 'UNCERTAIN',
          sourceImageId: images[0]?.id || 'img-custom',
          sourcePanel: 'Primary Label',
          bbox: { x: 15, y: 85, width: 70, height: 10 },
          legalReference: 'Rule 6(1)(f)',
        },
      ],
    };
  },
};
